name: Flutter CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  flutter_version: "2.5.x"
  java_version: "12.x"

jobs:
  flutter_test:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: ${{ env.java_version }}
      - name: Cache Flutter dependencies
        uses: actions/cache@v1
        with:
          path: /opt/hostedtoolcache/flutter
          key: ${{ runner.OS }}-flutter-install-cache-${{ env.flutter_version }}
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: ${{ env.flutter_version }}
      - name: Install dependencies
        run: flutter pub get
      - if: github.event_name == 'pull_request'
        run: flutter format --dry-run . --set-exit-if-changed
      - if: github.event_name == 'pull_request'
        run:  flutter analyze
      - if: github.event_name == 'push'
        run:  flutter test  
